-- MySQL Script generated by MySQL Workbench
-- Thu Jun  8 14:34:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instrutor` (
  `inst_id` INT NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`inst_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso` (
  `curso_id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `inst_id` INT NOT NULL,
  PRIMARY KEY (`curso_id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_curso_instrutor1_idx` (`inst_id` ASC) VISIBLE,
  CONSTRAINT `fk_curso_instrutor1`
    FOREIGN KEY (`inst_id`)
    REFERENCES `instrutor` (`inst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `departamento` (
  `dept_id` INT NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`dept_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funcionario` (
  `func_id` INT NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  `sobrenome` VARCHAR(30) NOT NULL,
  `celular` VARCHAR(20) NULL,
  `dept_id` INT NOT NULL,
  PRIMARY KEY (`func_id`),
  INDEX `fk_funcionario_departamento1_idx` (`dept_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_departamento1`
    FOREIGN KEY (`dept_id`)
    REFERENCES `departamento` (`dept_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `funcionario_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funcionario_curso` (
  `func_id` INT NOT NULL,
  `curso_id` INT NOT NULL,
  `concluido` TINYINT(1) NOT NULL DEFAULT 0,
  `avaliacao` FLOAT NULL,
  PRIMARY KEY (`func_id`, `curso_id`),
  INDEX `fk_funcionario_has_curso_curso1_idx` (`curso_id` ASC) VISIBLE,
  INDEX `fk_funcionario_has_curso_funcionario_idx` (`func_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_has_curso_funcionario`
    FOREIGN KEY (`func_id`)
    REFERENCES `funcionario` (`func_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_has_curso_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `curso` (`curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
